#---------------------------------------------------------------------
# Script Name:   TasselPluginWrappers.R
# Description:   Various tests with rJava
# Author:        Brandon Monier & Ed buckler
# Created:       2018-11-26 at 11:14:36
# Last Modified: 2018-12-11 at 21:55:45
#--------------------------------------------------------------------

#--------------------------------------------------------------------
# Detailed Purpose:
#    The main purpose of this Rscript to host to autogenerated wrappers
#   for TASSEL plugins
#--------------------------------------------------------------------

#' @title Filter Site Builder plugin
#' 
#' @description Filters a \code{GenotypeTable} class object. This function
#'    is similar to the \code{-FilterSiteBuilderPlugin} in TASSEL.
#' 
#' @param genotypeTable A \code{GenotypeTable} class object.
#' @param siteMinCount Site minimum count of alleles not unknown. Can take
#'    any whole number from \code{0} to \code{Inf}. Defaults to \code{0}.
#' @param siteMinAlleleFreq Site minimum minor allele frequency. Can take
#'    any real number from \code{0.0} to \code{1.0}. Defaults to \code{0.0}.
#' @param siteMaxAlleleFreq Site maximum minor allele frequency. Can take
#'    any real number from \code{0.0} to \code{1.0}. Defaults to \code{1.0}.
#' @param minHeterozygous Minimum heterozygous proportion. Can take any real
#'    number from \code{0.0} to \code{1.0}. Defaults to \code{0.0}
#' @param maxHeterozygous Maximum heterozygous proportion. Can take any real
#'    number from \code{0.0} to \code{1.0}. Defaults to \code{1.0}
#' @param startSite Start site. Defaults to \code{0}
#' @param endSite End site. Defaults to \code{0}
#' 
#' @rdname filterSiteBuilderPlugin
#' @name filterSiteBuilderPlugin
#' @importFrom rJava .jnew
#' @export
filterSiteBuilderPlugin <- function(genotypeTable,
                                    siteMinCount = 0,
                                    siteMinAlleleFreq = 0.0,
                                    siteMaxAlleleFreq = 1.0,
                                    minHeterozygous = 0.0,
                                    maxHeterozygous = 1.0,
                                    startSite = 0,
                                    endSite = 0
) {
  # Unwrap the java object if necessary
  if(is(genotypeTable,"GenotypeTable") == TRUE) {
    genotypeTable <- genotypeTable@jtsGenotypeTable
  }
  plugin <- rJava::.jnew("net.maizegenetics.analysis.filter.FilterSiteBuilderPlugin")
  plugin$setParameter("siteMinCount",toString(siteMinCount))
  plugin$setParameter("siteMinAlleleFreq",toString(siteMinAlleleFreq))
  plugin$setParameter("siteMaxAlleleFreq",toString(siteMaxAlleleFreq))
  plugin$setParameter("minHeterozygous",toString(minHeterozygous))
  plugin$setParameter("maxHeterozygous",toString(maxHeterozygous))
  plugin$setParameter("startSite",toString(startSite))
  plugin$setParameter("endSite",toString(endSite))
  
  filteredGT <- plugin$runPlugin(genotypeTable)
  #rewrap the object
  new(
    Class = "GenotypeTable",
    #todo come up with better name
    name = paste0("Filtered:"),
    jtsGenotypeTable = filteredGT
  )
}
